### ISSUE TITLE
Incorrect modal footer padding set to 0 when opening a modal with an action bar from a modal without an action bar

### ISSUE THREAD

**Issue by Blackbaud-StewartStephens** [blackbaud/skyux-action-bars#24]
- My Page
- - My outer modal (without action bar)
- - - My inner modal (with action bar)

### Expected behavior
Opening nested modals should not impact the style of their parent modals.

### Actual behavior
When opening "my outer modal" from "my page", the footer of "my outer modal" appears correctly.  When "my inner modal" is opened, the footer of "my outer modal" has its padding removed, while the footer of "my inner modal" does not, resulting in incorrect footer padding for both modals.

![image](https://user-images.githubusercontent.com/12860297/69090531-f093d580-0a16-11ea-8c0b-74fae15901b2.png)

### Steps to reproduce
See styleModalFooter: https://github.com/blackbaud/skyux-action-bars/blob/master/src/app/public/modules/summary-action-bar/summary-action-bar-adapter.service.ts

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.1.3`
