### ISSUE TITLE
Summary Action Bar Covers Autocomplete Results

### ISSUE THREAD

**Issue by Blackbaud-StewartStephens** [blackbaud/skyux-action-bars#27]
### Expected behavior
Summary action bars should not cover elements on the page.

### Actual behavior
Summary action bar covers the autocomplete results.  It looks like this is the result of z-index: 999 on .sky-summary-action-bar and .sky-summary-action-bar-actions.

![image](https://user-images.githubusercontent.com/12860297/69347143-f91c2400-0c41-11ea-8528-8911a0169585.png)

**Comment by Blackbaud-TrevorBurch** [comment]
Fixed via `skyux/modals` version `3.1.2`
