### ISSUE TITLE
extra white space is rendering between buttons

### ISSUE THREAD

**Issue by Blackbaud-ToddRoberts** [blackbaud/skyux-action-bars#7]
### Expected behavior
Buttons are defined with 10px right margin.

### Actual behavior
Additional whitespace is rendering despite margin set correctly.

**Comment by Blackbaud-TrevorBurch** [comment]
We need to look into possibly changing the actions to use flex for positioning instead of inline block. The `inline-block` styling renders whitespace due to any spaces at the end of the file. Flex would fix this.

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.0.1`
